name: DontSwear
version: 1.0
description: Prevent swearing in chat.
author: Lanky_Lord
website: https://github.com/LankyLord/DontSwear

main: com.github.lankylord.DontSwear.DontSwear
database: false

commands:
  swearadd:
    description: Add a swearword to the blacklist.
    permission: DontSwear.admin
    
permissions:
  DontSwear.*:
    description: All DontSwear permissions.
    children:
      DontSwear.admin: true
      DontSwear.bypass: true
  DontSwear.admin:
    description: Allows you to modify the blacklist.
    default: op
  DontSwear.bypass:
    description: Allows you to bypass the chat filter.
    default: op