name: DontSwear
version: 2.0
description: Prevent swearing in chat.
author: Lanky_Lord
website: https://github.com/LankyLord/DontSwear

main: net.lankylord.dontswear.DontSwear
database: false

commands:
  addswear:
    description: Add a swearword to the blacklist.
    permission: dontswear.admin
  delswear:
    description: Remove a swearword from the blacklist.
    permission: dontswear.admin
    
permissions:
  DontSwear.*:
    description: All DontSwear permissions.
    children:
      DontSwear.admin: true
      DontSwear.bypass: true
  DontSwear.admin:
    description: Allows you to modify the blacklist.
    default: op
  DontSwear.bypass:
    description: Allows you to bypass the chat filter.
    default: op