name: AntiSwear
version: 1.0
description: Prevent swearing in chat.
author: Lanky_Lord
website: https://github.com/LankyLord/AntiSwear

main: com.github.lankylord.AntiSwear.AntiSwear
database: false

commands:
  swearadd:
    description: Add a swearword to the blacklist.
    permission: AntiSwear.admin
    
permissions:
  AntiSwear.*:
    description: All AntiSwear permissions.
    children:
      AntiSwear.admin: true
      AntiSwear.bypass: true
  AntiSwear.admin:
    description: Allows you to modify the blacklist.
    default: op
  AntiSwear.bypass:
    description: Allows you to bypass the chat filter.
    default: op